name: firehol-ipset

on:
  schedule:
    - cron: '* * * * *'  # Runs at 00:00 UTC every day

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests tqdm

      - name: Run script
        run: python firehol-ipset.py # Replace 'your_script.py' with the name of your Python script
